version: '3.8'

services:
  # Almacenamiento NoSQL Obligatorio para Acme Ltd
  database:
    image: mongo:7.0
    container_name: acme_nosql_dwh
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: